/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SmartAttachmentsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  resourceFolderName: "resources",
  linkFormat: "wikilink" /* WIKILINK */,
  autoRenameDuplicates: true,
  imageSubFolder: "images",
  otherFilesSubFolder: "files"
};
var FILE_TYPE_MAP = {
  // Images
  "jpg": "images",
  "jpeg": "images",
  "png": "images",
  "gif": "images",
  "webp": "images",
  "svg": "images",
  "bmp": "images",
  "ico": "images",
  // Audio
  "mp3": "audio",
  "wav": "audio",
  "ogg": "audio",
  "flac": "audio",
  "m4a": "audio",
  // Video
  "mp4": "videos",
  "webm": "videos",
  "mov": "videos",
  "avi": "videos",
  "mkv": "videos",
  // Documents
  "pdf": "documents",
  "doc": "documents",
  "docx": "documents",
  "xls": "documents",
  "xlsx": "documents",
  "ppt": "documents",
  "pptx": "documents",
  // Archives
  "zip": "archives",
  "rar": "archives",
  "7z": "archives",
  "tar": "archives",
  "gz": "archives",
  // Code
  "js": "code",
  "ts": "code",
  "py": "code",
  "java": "code",
  "cpp": "code",
  "c": "code",
  "go": "code",
  "rs": "code",
  "html": "code",
  "css": "code",
  "json": "code",
  "xml": "code",
  "yaml": "code",
  "yml": "code",
  "sql": "code",
  "sh": "code",
  "bat": "code",
  "ps1": "code"
};

// src/settings-tab.ts
var import_obsidian = require("obsidian");
var SmartAttachmentsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Smart Attachments Settings" });
    new import_obsidian.Setting(containerEl).setName("Resource folder name").setDesc("The name of the folder where attachments will be stored (will be created as sibling to your vault)").addText((text) => text.setPlaceholder("resources").setValue(this.plugin.settings.resourceFolderName).onChange(async (value) => {
      this.plugin.settings.resourceFolderName = value || "resources";
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Link format").setDesc("How links to attachments should be formatted in your notes").addDropdown((dropdown) => dropdown.addOption("wikilink" /* WIKILINK */, "WikiLinks (![[path/to/file.png]])").addOption("markdown" /* MARKDOWN */, "Markdown (![alt](path/to/file.png))").setValue(this.plugin.settings.linkFormat).onChange(async (value) => {
      this.plugin.settings.linkFormat = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto-rename duplicates").setDesc("When a file with the same name exists, automatically rename it (e.g., image.png \u2192 image-1.png)").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoRenameDuplicates).onChange(async (value) => {
      this.plugin.settings.autoRenameDuplicates = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "How it works" });
    const infoDiv = containerEl.createDiv();
    infoDiv.createEl("p", {
      text: "When you paste or drop files into a markdown note, they will be organized in the following structure:"
    });
    const codeBlock = infoDiv.createEl("pre");
    codeBlock.createEl("code", {
      text: `your-vault/
\u251C\u2500\u2500 notes/
\u2502   \u2514\u2500\u2500 project/
\u2502       \u2514\u2500\u2500 readme.md
\u2514\u2500\u2500 .obsidian/

resources/                    (sibling to vault)
\u2514\u2500\u2500 images/                   (organized by type)
    \u2514\u2500\u2500 notes/
        \u2514\u2500\u2500 project/
            \u2514\u2500\u2500 image.png     (same relative path as markdown)`
    });
    infoDiv.createEl("p", {
      text: "The plugin supports automatic organization by file type: images, audio, videos, documents, archives, and code files."
    });
  }
};

// src/handlers/paste-handler.ts
var import_obsidian3 = require("obsidian");

// src/utils/path-utils.ts
var import_obsidian2 = require("obsidian");
var PathUtils = class {
  /**
   * Get the file extension from a filename
   */
  static getFileExtension(filename) {
    const lastDot = filename.lastIndexOf(".");
    return lastDot === -1 ? "" : filename.slice(lastDot + 1).toLowerCase();
  }
  /**
   * Get the subfolder name based on file type
   */
  static getSubFolderByType(extension) {
    return FILE_TYPE_MAP[extension] || "files";
  }
  /**
   * Get the relative path of a markdown file from vault root
   */
  static getRelativePathFromVault(file) {
    const path = file.path;
    const lastSlash = path.lastIndexOf("/");
    return lastSlash === -1 ? "" : path.substring(0, lastSlash);
  }
  /**
   * Build the resource directory path
   * Returns: {vault-parent}/resources/{file-type}/{md-relative-path}/
   */
  static buildResourcePath(vault, mdFile, fileExtension, resourceFolderName) {
    const vaultRoot = this.getVaultRoot(vault);
    const subFolder = this.getSubFolderByType(fileExtension);
    const relativePath = this.getRelativePathFromVault(mdFile);
    const parts = [vaultRoot, "..", resourceFolderName, subFolder];
    if (relativePath) {
      parts.push(relativePath);
    }
    return parts.join("/");
  }
  /**
   * Get vault root path using FileSystemAdapter
   */
  static getVaultRoot(vault) {
    if (vault.adapter instanceof import_obsidian2.FileSystemAdapter) {
      return vault.adapter.getBasePath();
    }
    return vault.getName();
  }
  /**
   * Build the relative resource path for linking in markdown
   * Returns: resources/file-type/relative-path/filename
   */
  static buildResourceLinkPath(mdFile, fileExtension, resourceFolderName) {
    const subFolder = this.getSubFolderByType(fileExtension);
    const relativePath = this.getRelativePathFromVault(mdFile);
    const parts = [resourceFolderName, subFolder];
    if (relativePath) {
      parts.push(relativePath);
    }
    return parts.join("/");
  }
  /**
   * Generate a unique filename by adding numeric suffix if file exists
   * e.g., image.png -> image-1.png -> image-2.png
   */
  static generateUniqueFileName(baseName, existingFiles) {
    if (!existingFiles.has(baseName)) {
      return baseName;
    }
    const lastDot = baseName.lastIndexOf(".");
    const name = lastDot === -1 ? baseName : baseName.substring(0, lastDot);
    const ext = lastDot === -1 ? "" : baseName.substring(lastDot);
    let counter = 1;
    let newName = `${name}-${counter}${ext}`;
    while (existingFiles.has(newName)) {
      counter++;
      newName = `${name}-${counter}${ext}`;
    }
    return newName;
  }
  /**
   * Sanitize filename to remove invalid characters
   */
  static sanitizeFileName(fileName) {
    return fileName.replace(/[<>:"/\\|?*]/g, "_").trim();
  }
};

// src/utils/link-utils.ts
var LinkUtils = class {
  /**
   * Generate WikiLink format: ![[path/to/file.png]]
   */
  static toWikiLink(resourcePath, altText) {
    return `![[${resourcePath}]]`;
  }
  /**
   * Generate standard Markdown format: ![alt](path/to/file.png)
   */
  static toMarkdownLink(resourcePath, altText = "") {
    return `![${altText}](${resourcePath})`;
  }
  /**
   * Generate link based on configured format
   */
  static generateLink(format, resourcePath, fileName) {
    const altText = fileName.replace(/\.[^/.]+$/, "");
    switch (format) {
      case "wikilink" /* WIKILINK */:
        return this.toWikiLink(resourcePath);
      case "markdown" /* MARKDOWN */:
        return this.toMarkdownLink(resourcePath, altText);
      default:
        return this.toWikiLink(resourcePath);
    }
  }
};

// src/handlers/paste-handler.ts
var PasteHandler = class {
  constructor(vault, settings) {
    this.vault = vault;
    this.settings = settings;
  }
  /**
   * Handle paste event
   * Returns true if handled, false to let default handler process
   */
  async handle(evt, editor, mdFile) {
    var _a;
    const files = (_a = evt.clipboardData) == null ? void 0 : _a.files;
    if (!files || files.length === 0) {
      return false;
    }
    const supportedFiles = Array.from(files).filter((file) => this.isSupportedFile(file));
    if (supportedFiles.length === 0) {
      return false;
    }
    evt.preventDefault();
    evt.stopPropagation();
    try {
      for (const file of supportedFiles) {
        await this.processFile(file, editor, mdFile);
      }
      new import_obsidian3.Notice(`Successfully processed ${supportedFiles.length} file(s)`);
      return true;
    } catch (error) {
      console.error("Error processing pasted files:", error);
      new import_obsidian3.Notice(`Error processing files: ${error.message}`, 5e3);
      return true;
    }
  }
  /**
   * Check if file type is supported
   */
  isSupportedFile(file) {
    return true;
  }
  /**
   * Process a single file: save to resources and insert link
   */
  async processFile(file, editor, mdFile) {
    const extension = PathUtils.getFileExtension(file.name);
    const sanitizedName = PathUtils.sanitizeFileName(file.name);
    const resourceDir = PathUtils.buildResourcePath(
      this.vault,
      mdFile,
      extension,
      this.settings.resourceFolderName
    );
    const resourceLinkPath = PathUtils.buildResourceLinkPath(
      mdFile,
      extension,
      this.settings.resourceFolderName
    );
    await this.ensureDirectoryExists(resourceDir);
    const finalFileName = this.settings.autoRenameDuplicates ? await this.getUniqueFileName(resourceDir, sanitizedName) : sanitizedName;
    const fullPath = `${resourceDir}/${finalFileName}`;
    const arrayBuffer = await file.arrayBuffer();
    const uint8Array = new Uint8Array(arrayBuffer);
    await this.vault.adapter.writeBinary(fullPath, uint8Array);
    const fullResourcePath = `${resourceLinkPath}/${finalFileName}`;
    const link = LinkUtils.generateLink(
      this.settings.linkFormat,
      fullResourcePath,
      finalFileName
    );
    const cursor = editor.getCursor();
    editor.replaceRange(link, cursor);
    const newCursor = {
      line: cursor.line,
      ch: cursor.ch + link.length
    };
    editor.setCursor(newCursor);
    editor.replaceRange("\n", newCursor);
    editor.setCursor({
      line: newCursor.line + 1,
      ch: 0
    });
  }
  /**
   * Ensure the resource directory exists
   */
  async ensureDirectoryExists(dirPath) {
    try {
      const exists = await this.vault.adapter.exists(dirPath);
      if (!exists) {
        await this.vault.adapter.mkdir(dirPath);
      }
    } catch (error) {
      console.error("Error creating directory:", error);
      throw new Error(`Failed to create directory: ${dirPath}`);
    }
  }
  /**
   * Get a unique filename by checking existing files
   */
  async getUniqueFileName(dirPath, fileName) {
    try {
      const list = await this.vault.adapter.list(dirPath);
      const existingFiles = new Set(list.files.map((f) => {
        const parts = f.split("/");
        return parts[parts.length - 1];
      }));
      return PathUtils.generateUniqueFileName(fileName, existingFiles);
    } catch (error) {
      return fileName;
    }
  }
};

// src/handlers/drop-handler.ts
var import_obsidian4 = require("obsidian");
var DropHandler = class {
  constructor(vault, settings) {
    this.vault = vault;
    this.settings = settings;
  }
  /**
   * Handle drop event
   * Returns true if handled, false to let default handler process
   */
  async handle(evt, editor, mdFile) {
    var _a;
    const files = (_a = evt.dataTransfer) == null ? void 0 : _a.files;
    if (!files || files.length === 0) {
      return false;
    }
    const droppedFiles = Array.from(files);
    if (droppedFiles.length === 0) {
      return false;
    }
    evt.preventDefault();
    evt.stopPropagation();
    try {
      for (const file of droppedFiles) {
        await this.processFile(file, editor, mdFile, evt);
      }
      new import_obsidian4.Notice(`Successfully processed ${droppedFiles.length} file(s)`);
      return true;
    } catch (error) {
      console.error("Error processing dropped files:", error);
      new import_obsidian4.Notice(`Error processing files: ${error.message}`, 5e3);
      return true;
    }
  }
  /**
   * Process a single file: save to resources and insert link
   */
  async processFile(file, editor, mdFile, evt) {
    const extension = PathUtils.getFileExtension(file.name);
    const sanitizedName = PathUtils.sanitizeFileName(file.name);
    const resourceDir = PathUtils.buildResourcePath(
      this.vault,
      mdFile,
      extension,
      this.settings.resourceFolderName
    );
    const resourceLinkPath = PathUtils.buildResourceLinkPath(
      mdFile,
      extension,
      this.settings.resourceFolderName
    );
    await this.ensureDirectoryExists(resourceDir);
    const finalFileName = this.settings.autoRenameDuplicates ? await this.getUniqueFileName(resourceDir, sanitizedName) : sanitizedName;
    const fullPath = `${resourceDir}/${finalFileName}`;
    const arrayBuffer = await file.arrayBuffer();
    const uint8Array = new Uint8Array(arrayBuffer);
    await this.vault.adapter.writeBinary(fullPath, uint8Array);
    const fullResourcePath = `${resourceLinkPath}/${finalFileName}`;
    const link = LinkUtils.generateLink(
      this.settings.linkFormat,
      fullResourcePath,
      finalFileName
    );
    const dropPos = editor.getCursor();
    editor.replaceRange(link, dropPos);
    const newCursor = {
      line: dropPos.line,
      ch: dropPos.ch + link.length
    };
    editor.setCursor(newCursor);
    editor.replaceRange("\n", newCursor);
    editor.setCursor({
      line: newCursor.line + 1,
      ch: 0
    });
  }
  /**
   * Ensure the resource directory exists
   */
  async ensureDirectoryExists(dirPath) {
    try {
      const exists = await this.vault.adapter.exists(dirPath);
      if (!exists) {
        await this.vault.adapter.mkdir(dirPath);
      }
    } catch (error) {
      console.error("Error creating directory:", error);
      throw new Error(`Failed to create directory: ${dirPath}`);
    }
  }
  /**
   * Get a unique filename by checking existing files
   */
  async getUniqueFileName(dirPath, fileName) {
    try {
      const list = await this.vault.adapter.list(dirPath);
      const existingFiles = new Set(list.files.map((f) => {
        const parts = f.split("/");
        return parts[parts.length - 1];
      }));
      return PathUtils.generateUniqueFileName(fileName, existingFiles);
    } catch (error) {
      return fileName;
    }
  }
};

// src/main.ts
var SmartAttachmentsPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.pasteHandler = new PasteHandler(this.app.vault, this.settings);
    this.dropHandler = new DropHandler(this.app.vault, this.settings);
    this.registerEvent(
      this.app.workspace.on("editor-paste", (evt, editor, view) => {
        this.handlePaste(evt, editor, view);
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-drop", (evt, editor, view) => {
        this.handleDrop(evt, editor, view);
      })
    );
    this.addSettingTab(new SmartAttachmentsSettingTab(this.app, this));
    console.log("Smart Attachments plugin loaded");
  }
  onunload() {
    console.log("Smart Attachments plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.pasteHandler = new PasteHandler(this.app.vault, this.settings);
    this.dropHandler = new DropHandler(this.app.vault, this.settings);
  }
  /**
   * Handle paste event
   */
  async handlePaste(evt, editor, view) {
    const mdFile = view.file;
    if (!mdFile) {
      return;
    }
    if (mdFile.extension !== "md") {
      return;
    }
    const handled = await this.pasteHandler.handle(evt, editor, mdFile);
    if (handled) {
      return;
    }
  }
  /**
   * Handle drop event
   */
  async handleDrop(evt, editor, view) {
    const mdFile = view.file;
    if (!mdFile) {
      return;
    }
    if (mdFile.extension !== "md") {
      return;
    }
    const handled = await this.dropHandler.handle(evt, editor, mdFile);
    if (handled) {
      return;
    }
  }
};
