/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  createDirectoryMovePlan: () => createDirectoryMovePlan,
  createNoteMovePlan: () => createNoteMovePlan,
  default: () => SmartAttachmentsPlugin,
  extractManagedResourceLinks: () => extractManagedResourceLinks,
  formatResourceSyncSummary: () => formatResourceSyncSummary,
  getManagedResourceDirPrefixes: () => getManagedResourceDirPrefixes,
  isManagedNoteLikePath: () => isManagedNoteLikePath,
  listManagedResourcePaths: () => listManagedResourcePaths,
  mapManagedResourceDir: () => mapManagedResourceDir,
  rewriteDirectoryMoveContent: () => rewriteDirectoryMoveContent,
  rewriteManagedResourcePrefix: () => rewriteManagedResourcePrefix
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  resourceFolderName: "resources",
  linkFormat: "wikilink" /* WIKILINK */,
  autoRenameDuplicates: true,
  imageSubFolder: "images",
  otherFilesSubFolder: "files",
  autoCleanupOnExit: false,
  showCleanupConfirmation: true
};
var FILE_TYPE_MAP = {
  // Images
  "jpg": "images",
  "jpeg": "images",
  "png": "images",
  "gif": "images",
  "webp": "images",
  "svg": "images",
  "bmp": "images",
  "ico": "images",
  // Audio
  "mp3": "audio",
  "wav": "audio",
  "ogg": "audio",
  "flac": "audio",
  "m4a": "audio",
  // Video
  "mp4": "videos",
  "webm": "videos",
  "mov": "videos",
  "avi": "videos",
  "mkv": "videos",
  // Documents
  "pdf": "documents",
  "doc": "documents",
  "docx": "documents",
  "xls": "documents",
  "xlsx": "documents",
  "ppt": "documents",
  "pptx": "documents",
  // Archives
  "zip": "archives",
  "rar": "archives",
  "7z": "archives",
  "tar": "archives",
  "gz": "archives",
  // Code
  "js": "code",
  "ts": "code",
  "py": "code",
  "java": "code",
  "cpp": "code",
  "c": "code",
  "go": "code",
  "rs": "code",
  "html": "code",
  "css": "code",
  "json": "code",
  "xml": "code",
  "yaml": "code",
  "yml": "code",
  "sql": "code",
  "sh": "code",
  "bat": "code",
  "ps1": "code"
};

// src/settings-tab.ts
var import_obsidian = require("obsidian");
var SmartAttachmentsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Resource folder name").setDesc("The name of the folder where attachments will be stored (will be created as sibling to your vault)").addText((text) => text.setPlaceholder("Resources").setValue(this.plugin.settings.resourceFolderName).onChange((value) => {
      this.plugin.settings.resourceFolderName = value || "resources";
      void this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Link format").setDesc("How links to attachments should be formatted in your notes").addDropdown((dropdown) => dropdown.addOption("wikilink" /* WIKILINK */, "Wiki links (![[path/to/file.png]])").addOption("markdown" /* MARKDOWN */, "Markdown links (![alt](path/to/file.png))").setValue(this.plugin.settings.linkFormat).onChange((value) => {
      this.plugin.settings.linkFormat = value;
      void this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Auto-rename duplicates").setDesc("When a file with the same name exists, automatically rename it (e.g., image.png \u2192 image-1.png)").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoRenameDuplicates).onChange((value) => {
      this.plugin.settings.autoRenameDuplicates = value;
      void this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Cleanup").setHeading();
    new import_obsidian.Setting(containerEl).setName("Show cleanup confirmation").setDesc("Show a confirmation dialog before deleting orphaned attachments").addToggle((toggle) => toggle.setValue(this.plugin.settings.showCleanupConfirmation).onChange((value) => {
      this.plugin.settings.showCleanupConfirmation = value;
      void this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Clean up orphaned attachments").setDesc("Scan and delete attachment files that are not referenced in any Markdown file").addButton((button) => button.setButtonText("Clean up now").setCta().onClick(() => {
      void this.plugin.cleanupOrphanedAttachments();
    }));
    new import_obsidian.Setting(containerEl).setName("How it works").setHeading();
    const infoDiv = containerEl.createDiv();
    infoDiv.createEl("p", {
      text: "When you paste or drop files into a Markdown note, they will be organized in the following structure:"
    });
    const codeBlock = infoDiv.createEl("pre");
    codeBlock.createEl("code", {
      text: `your-vault/
\u251C\u2500\u2500 notes/
\u2502   \u2514\u2500\u2500 project/
\u2502       \u2514\u2500\u2500 readme.md
\u2514\u2500\u2500 .obsidian/

resources/                    (sibling to vault)
\u2514\u2500\u2500 images/                   (organized by type)
    \u2514\u2500\u2500 notes/
        \u2514\u2500\u2500 project/
            \u2514\u2500\u2500 image.png     (same relative path as markdown)`
    });
    infoDiv.createEl("p", {
      text: "The plugin supports automatic organization by file type: images, audio, videos, documents, archives, and code files."
    });
  }
};

// src/handlers/paste-handler.ts
var import_obsidian2 = require("obsidian");

// src/utils/path-utils.ts
var MANAGED_RESOURCE_TYPES = ["images", "audio", "videos", "documents", "archives", "code", "files"];
var PathUtils = class {
  /**
   * Get the file extension from a filename
   */
  static getFileExtension(filename) {
    const lastDot = filename.lastIndexOf(".");
    return lastDot === -1 ? "" : filename.slice(lastDot + 1).toLowerCase();
  }
  /**
   * Get the subfolder name based on file type
   */
  static getSubFolderByType(extension) {
    return FILE_TYPE_MAP[extension] || "files";
  }
  /**
   * Get the relative path of a markdown file from vault root
   */
  static getRelativePathFromVault(file) {
    const path = file.path;
    const lastSlash = path.lastIndexOf("/");
    return lastSlash === -1 ? "" : path.substring(0, lastSlash);
  }
  /**
   * Build the resource directory path
   * Returns: {vault-parent}/resources/{file-type}/{md-relative-path}/
   */
  static buildResourcePath(vault, mdFile, fileExtension, resourceFolderName) {
    const resourceRoot = this.getResourceRoot(vault, resourceFolderName);
    const subFolder = this.getSubFolderByType(fileExtension);
    const relativePath = this.getRelativePathFromVault(mdFile);
    const parts = [resourceRoot, subFolder];
    if (relativePath) {
      parts.push(relativePath);
    }
    return parts.join("/");
  }
  /**
   * Get vault root path using FileSystemAdapter
   */
  static getVaultRoot(vault) {
    const adapter = vault.adapter;
    if (typeof adapter.getBasePath === "function") {
      return adapter.getBasePath();
    }
    return vault.getName();
  }
  static getResourceRoot(vault, resourceFolderName) {
    const vaultRoot = this.getVaultRoot(vault);
    const absoluteResourceRoot = `${vaultRoot}/../${resourceFolderName}`;
    return vaultRoot.includes(`/${resourceFolderName}`) ? vaultRoot : absoluteResourceRoot;
  }
  static resolveManagedResourcePath(vault, resourceFolderName, resourcePath) {
    const vaultRoot = this.getVaultRoot(vault);
    const resourceRelativePath = resourcePath.replace(/^resources\//, `${resourceFolderName}/`);
    return vaultRoot.includes(`/${resourceFolderName}`) ? `${vaultRoot}/${resourceRelativePath}` : `${vaultRoot}/../${resourceRelativePath}`;
  }
  /**
   * Build the relative resource path for linking in markdown
   * Returns: resources/file-type/relative-path/filename
   */
  static buildResourceLinkPath(mdFile, fileExtension, resourceFolderName) {
    const subFolder = this.getSubFolderByType(fileExtension);
    const relativePath = this.getRelativePathFromVault(mdFile);
    const parts = [resourceFolderName, subFolder];
    if (relativePath) {
      parts.push(relativePath);
    }
    return parts.join("/");
  }
  /**
   * Generate a unique filename by adding numeric suffix if file exists
   * e.g., image.png -> image-1.png -> image-2.png
   */
  static generateUniqueFileName(baseName, existingFiles) {
    if (!existingFiles.has(baseName)) {
      return baseName;
    }
    const lastDot = baseName.lastIndexOf(".");
    const name = lastDot === -1 ? baseName : baseName.substring(0, lastDot);
    const ext = lastDot === -1 ? "" : baseName.substring(lastDot);
    let counter = 1;
    let newName = `${name}-${counter}${ext}`;
    while (existingFiles.has(newName)) {
      counter++;
      newName = `${name}-${counter}${ext}`;
    }
    return newName;
  }
  /**
   * Sanitize filename to remove invalid characters
   */
  static sanitizeFileName(fileName) {
    return fileName.replace(/[<>:"/\\|?*]/g, "_").trim();
  }
  static getManagedResourceTypes() {
    return MANAGED_RESOURCE_TYPES;
  }
  static getManagedResourceDirPrefixes(relativeDir) {
    return MANAGED_RESOURCE_TYPES.map((type) => `resources/${type}${relativeDir ? `/${relativeDir}` : ""}`);
  }
  static mapManagedResourceDir(resourceDir, oldDir, newDir) {
    const oldSuffix = oldDir ? `/${oldDir}` : "";
    const newSuffix = newDir ? `/${newDir}` : "";
    return resourceDir.endsWith(oldSuffix) ? `${resourceDir.slice(0, resourceDir.length - oldSuffix.length)}${newSuffix}` : resourceDir;
  }
};

// src/utils/link-utils.ts
var LinkUtils = class {
  /**
   * Generate WikiLink format: ![[path/to/file.png]]
   */
  static toWikiLink(resourcePath, altText) {
    return `![[${resourcePath}]]`;
  }
  /**
   * Generate standard Markdown format: ![alt](path/to/file.png)
   */
  static toMarkdownLink(resourcePath, altText = "") {
    return `![${altText}](${resourcePath})`;
  }
  /**
   * Generate link based on configured format
   */
  static generateLink(format, resourcePath, fileName) {
    const altText = fileName.replace(/\.[^/.]+$/, "");
    switch (format) {
      case "wikilink" /* WIKILINK */:
        return this.toWikiLink(resourcePath);
      case "markdown" /* MARKDOWN */:
        return this.toMarkdownLink(resourcePath, altText);
      default:
        return this.toWikiLink(resourcePath);
    }
  }
};

// src/handlers/paste-handler.ts
var PasteHandler = class {
  constructor(vault, settings) {
    this.vault = vault;
    this.settings = settings;
  }
  /**
   * Handle paste event
   * Returns true if handled, false to let default handler process
   */
  async handle(evt, editor, noteFile) {
    var _a;
    const files = (_a = evt.clipboardData) == null ? void 0 : _a.files;
    if (!files || files.length === 0) {
      return false;
    }
    const supportedFiles = Array.from(files);
    if (supportedFiles.length === 0) {
      return false;
    }
    evt.preventDefault();
    evt.stopPropagation();
    try {
      for (const file of supportedFiles) {
        await this.processFile(file, editor, noteFile);
      }
      new import_obsidian2.Notice(`Successfully processed ${supportedFiles.length} file(s)`);
      return true;
    } catch (error) {
      console.error("Error processing pasted files:", error);
      new import_obsidian2.Notice(`Error processing files: ${error.message}`, 5e3);
      return true;
    }
  }
  /**
   * Process a single file: save to resources and insert link
   */
  async processFile(file, editor, noteFile) {
    const extension = PathUtils.getFileExtension(file.name);
    const sanitizedName = PathUtils.sanitizeFileName(file.name);
    const resourceDir = PathUtils.buildResourcePath(
      this.vault,
      noteFile,
      extension,
      this.settings.resourceFolderName
    );
    const resourceLinkPath = PathUtils.buildResourceLinkPath(
      noteFile,
      extension,
      this.settings.resourceFolderName
    );
    await this.ensureDirectoryExists(resourceDir);
    const finalFileName = this.settings.autoRenameDuplicates ? await this.getUniqueFileName(resourceDir, sanitizedName) : sanitizedName;
    const fullPath = `${resourceDir}/${finalFileName}`;
    const arrayBuffer = await file.arrayBuffer();
    const uint8Array = new Uint8Array(arrayBuffer);
    await this.vault.adapter.writeBinary(fullPath, uint8Array);
    const fullResourcePath = `${resourceLinkPath}/${finalFileName}`;
    const link = LinkUtils.generateLink(
      this.settings.linkFormat,
      fullResourcePath,
      finalFileName
    );
    const cursor = editor.getCursor();
    editor.replaceRange(link, cursor);
    const newCursor = {
      line: cursor.line,
      ch: cursor.ch + link.length
    };
    editor.setCursor(newCursor);
    editor.replaceRange("\n", newCursor);
    editor.setCursor({
      line: newCursor.line + 1,
      ch: 0
    });
  }
  /**
   * Ensure the resource directory exists
   */
  async ensureDirectoryExists(dirPath) {
    try {
      const exists = await this.vault.adapter.exists(dirPath);
      if (!exists) {
        await this.vault.adapter.mkdir(dirPath);
      }
    } catch (error) {
      console.error("Error creating directory:", error);
      throw new Error(`Failed to create directory: ${dirPath}`);
    }
  }
  /**
   * Get a unique filename by checking existing files
   */
  async getUniqueFileName(dirPath, fileName) {
    try {
      const list = await this.vault.adapter.list(dirPath);
      const existingFiles = new Set(list.files.map((f) => {
        const parts = f.split("/");
        return parts[parts.length - 1];
      }));
      return PathUtils.generateUniqueFileName(fileName, existingFiles);
    } catch (e) {
      return fileName;
    }
  }
};

// src/handlers/drop-handler.ts
var import_obsidian3 = require("obsidian");
var DropHandler = class {
  constructor(vault, settings) {
    this.vault = vault;
    this.settings = settings;
  }
  /**
   * Handle drop event
   * Returns true if handled, false to let default handler process
   */
  async handle(evt, editor, noteFile) {
    var _a;
    const files = (_a = evt.dataTransfer) == null ? void 0 : _a.files;
    if (!files || files.length === 0) {
      return false;
    }
    const droppedFiles = Array.from(files);
    if (droppedFiles.length === 0) {
      return false;
    }
    evt.preventDefault();
    evt.stopPropagation();
    try {
      for (const file of droppedFiles) {
        await this.processFile(file, editor, noteFile);
      }
      new import_obsidian3.Notice(`Successfully processed ${droppedFiles.length} file(s)`);
      return true;
    } catch (error) {
      console.error("Error processing dropped files:", error);
      new import_obsidian3.Notice(`Error processing files: ${error.message}`, 5e3);
      return true;
    }
  }
  /**
   * Process a single file: save to resources and insert link
   */
  async processFile(file, editor, noteFile) {
    const extension = PathUtils.getFileExtension(file.name);
    const sanitizedName = PathUtils.sanitizeFileName(file.name);
    const resourceDir = PathUtils.buildResourcePath(
      this.vault,
      noteFile,
      extension,
      this.settings.resourceFolderName
    );
    const resourceLinkPath = PathUtils.buildResourceLinkPath(
      noteFile,
      extension,
      this.settings.resourceFolderName
    );
    await this.ensureDirectoryExists(resourceDir);
    const finalFileName = this.settings.autoRenameDuplicates ? await this.getUniqueFileName(resourceDir, sanitizedName) : sanitizedName;
    const fullPath = `${resourceDir}/${finalFileName}`;
    const arrayBuffer = await file.arrayBuffer();
    const uint8Array = new Uint8Array(arrayBuffer);
    await this.vault.adapter.writeBinary(fullPath, uint8Array);
    const fullResourcePath = `${resourceLinkPath}/${finalFileName}`;
    const link = LinkUtils.generateLink(
      this.settings.linkFormat,
      fullResourcePath,
      finalFileName
    );
    const dropPos = editor.getCursor();
    editor.replaceRange(link, dropPos);
    const newCursor = {
      line: dropPos.line,
      ch: dropPos.ch + link.length
    };
    editor.setCursor(newCursor);
    editor.replaceRange("\n", newCursor);
    editor.setCursor({
      line: newCursor.line + 1,
      ch: 0
    });
  }
  /**
   * Ensure the resource directory exists
   */
  async ensureDirectoryExists(dirPath) {
    try {
      const exists = await this.vault.adapter.exists(dirPath);
      if (!exists) {
        await this.vault.adapter.mkdir(dirPath);
      }
    } catch (error) {
      console.error("Error creating directory:", error);
      throw new Error(`Failed to create directory: ${dirPath}`);
    }
  }
  /**
   * Get a unique filename by checking existing files
   */
  async getUniqueFileName(dirPath, fileName) {
    try {
      const list = await this.vault.adapter.list(dirPath);
      const existingFiles = new Set(list.files.map((f) => {
        const parts = f.split("/");
        return parts[parts.length - 1];
      }));
      return PathUtils.generateUniqueFileName(fileName, existingFiles);
    } catch (e) {
      return fileName;
    }
  }
};

// src/utils/cleanup-utils.ts
var import_obsidian4 = require("obsidian");

// src/utils/managed-link-utils.ts
var WIKI_LINK_REGEX = /!?(\[\[(resources\/[^\]]+)\]\])/g;
var MARKDOWN_LINK_REGEX = /!?(\[[^\]]*\]\((resources\/[^)]+)\))/g;
function extractManagedResourceLinks(content) {
  const matches = [];
  for (const regex of [WIKI_LINK_REGEX, MARKDOWN_LINK_REGEX]) {
    regex.lastIndex = 0;
    let match;
    while ((match = regex.exec(content)) !== null) {
      matches.push({
        fullMatch: match[1],
        resourcePath: match[2]
      });
    }
  }
  return matches;
}
function listManagedResourcePaths(content) {
  return extractManagedResourceLinks(content).map((link) => link.resourcePath);
}
function rewriteManagedResourcePrefix(content, oldDir, newDir) {
  const resourceTypes = ["images", "audio", "videos", "documents", "archives", "code", "files"];
  let updatedCount = 0;
  let nextContent = content;
  for (const type of resourceTypes) {
    const from = `resources/${type}${oldDir ? `/${oldDir}` : ""}`;
    const to = `resources/${type}${newDir ? `/${newDir}` : ""}`;
    if (!nextContent.includes(from)) {
      continue;
    }
    const occurrences = nextContent.split(from).length - 1;
    nextContent = nextContent.split(from).join(to);
    updatedCount += occurrences;
  }
  return { content: nextContent, updatedCount };
}

// src/utils/cleanup-utils.ts
var CleanupUtils = class {
  constructor(vault, settings) {
    this.vault = vault;
    this.settings = settings;
  }
  /**
   * Scan for orphaned attachment files
   */
  async scanOrphanedFiles() {
    const orphanedFiles = [];
    const markdownFiles = this.vault.getMarkdownFiles();
    const referencedFiles = await this.getAllReferencedFiles(markdownFiles);
    const resourceFiles = await this.getAllResourceFiles();
    for (const resourceFile of resourceFiles) {
      if (!referencedFiles.has(resourceFile)) {
        const stat = await this.vault.adapter.stat(resourceFile);
        if (stat) {
          orphanedFiles.push({
            path: resourceFile,
            name: resourceFile.split("/").pop() || resourceFile,
            size: stat.size,
            lastModified: stat.ctime
          });
        }
      }
    }
    const totalSize = orphanedFiles.reduce((sum, f) => sum + f.size, 0);
    return {
      orphanedFiles,
      totalSize,
      deletedCount: 0,
      deletedSize: 0
    };
  }
  /**
   * Delete orphaned files
   */
  async deleteOrphanedFiles(files) {
    let deletedCount = 0;
    let deletedSize = 0;
    for (const file of files) {
      try {
        await this.vault.adapter.remove(file.path);
        deletedCount++;
        deletedSize += file.size;
      } catch (e) {
        console.error(`Failed to delete ${file.path}`);
      }
    }
    return { deletedCount, deletedSize };
  }
  /**
   * Get all resource files in the resources directory
   */
  async getAllResourceFiles() {
    const resourceFiles = [];
    const vaultRoot = this.getVaultRoot();
    const resourceDir = `${vaultRoot}/../${this.settings.resourceFolderName}`;
    try {
      await this.collectFilesRecursive(resourceDir, resourceFiles);
    } catch (e) {
      console.debug("Resource directory not found or empty");
    }
    return resourceFiles;
  }
  /**
   * Recursively collect files from directory
   */
  async collectFilesRecursive(dir, files) {
    try {
      const list = await this.vault.adapter.list(dir);
      for (const file of list.files) {
        files.push(file);
      }
      for (const folder of list.folders) {
        await this.collectFilesRecursive(folder, files);
      }
    } catch (e) {
    }
  }
  /**
   * Get all files referenced in markdown files
   */
  async getAllReferencedFiles(markdownFiles) {
    const referencedFiles = /* @__PURE__ */ new Set();
    for (const mdFile of markdownFiles) {
      const content = await this.vault.cachedRead(mdFile);
      const links = extractManagedResourceLinks(content);
      for (const link of links) {
        const fullPath = this.resolveResourcePath(link.resourcePath);
        if (fullPath) {
          referencedFiles.add(fullPath);
        }
      }
    }
    return referencedFiles;
  }
  /**
   * Get vault root path
   */
  getVaultRoot() {
    if (this.vault.adapter instanceof import_obsidian4.FileSystemAdapter) {
      return this.vault.adapter.getBasePath();
    }
    return "";
  }
  /**
   * Resolve resource path to full file system path
   */
  resolveResourcePath(resourcePath) {
    const vaultRoot = this.getVaultRoot();
    const fullPath = `${vaultRoot}/../${resourcePath}`;
    return fullPath;
  }
  /**
   * Format file size for display
   */
  static formatFileSize(bytes) {
    if (bytes < 1024)
      return `${bytes} B`;
    if (bytes < 1024 * 1024)
      return `${(bytes / 1024).toFixed(1)} KB`;
    if (bytes < 1024 * 1024 * 1024)
      return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
    return `${(bytes / (1024 * 1024 * 1024)).toFixed(1)} GB`;
  }
};
var CleanupConfirmModal = class extends import_obsidian4.Modal {
  constructor(app, orphanedFiles, totalSize, onConfirm) {
    super(app);
    this.orphanedFiles = orphanedFiles;
    this.totalSize = totalSize;
    this.onConfirm = onConfirm;
    this.result = false;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u6E05\u7406\u5B64\u7ACB\u9644\u4EF6" });
    contentEl.createEl("p", {
      text: `\u53D1\u73B0 ${this.orphanedFiles.length} \u4E2A\u672A\u88AB\u5F15\u7528\u7684\u9644\u4EF6\u6587\u4EF6\uFF0C\u5360\u7528\u7A7A\u95F4 ${CleanupUtils.formatFileSize(this.totalSize)}\u3002`
    });
    const listContainer = contentEl.createDiv({ cls: "smart-attachments-file-list" });
    for (const file of this.orphanedFiles) {
      const item = listContainer.createDiv({ cls: "smart-attachments-file-item" });
      item.createSpan({
        text: `${file.name} (${CleanupUtils.formatFileSize(file.size)})`,
        cls: "cleanup-file-item"
      });
    }
    contentEl.createEl("p", {
      text: "\u26A0\uFE0F \u8FD9\u4E9B\u6587\u4EF6\u5728\u60A8\u7684\u7B14\u8BB0\u4E2D\u672A\u88AB\u5F15\u7528\u3002\u5220\u9664\u540E\u5C06\u65E0\u6CD5\u6062\u590D\u3002",
      cls: "cleanup-warning"
    });
    const buttonContainer = contentEl.createDiv({ cls: "smart-attachments-button-container" });
    const cancelButton = buttonContainer.createEl("button", { text: "\u53D6\u6D88" });
    cancelButton.addEventListener("click", () => {
      this.close();
    });
    const confirmButton = buttonContainer.createEl("button", {
      text: `\u5220\u9664 ${this.orphanedFiles.length} \u4E2A\u6587\u4EF6`,
      cls: "mod-warning smart-attachments-error-button"
    });
    confirmButton.addEventListener("click", () => {
      this.result = true;
      this.onConfirm();
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var CleanupResultModal = class extends import_obsidian4.Modal {
  constructor(app, result) {
    super(app);
    this.result = result;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u6E05\u7406\u5B8C\u6210" });
    if (this.result.deletedCount === 0) {
      contentEl.createEl("p", { text: "\u6CA1\u6709\u6587\u4EF6\u88AB\u5220\u9664\u3002" });
    } else {
      contentEl.createEl("p", {
        text: `\u6210\u529F\u5220\u9664 ${this.result.deletedCount} \u4E2A\u6587\u4EF6\uFF0C\u91CA\u653E ${CleanupUtils.formatFileSize(this.result.deletedSize)} \u7A7A\u95F4\u3002`
      });
    }
    const okButton = contentEl.createEl("button", { text: "\u786E\u5B9A", cls: "mod-cta smart-attachments-margin-top" });
    okButton.addEventListener("click", () => {
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/utils/managed-note-utils.ts
function isManagedNoteLikePath(path) {
  const lastSlash = path.lastIndexOf("/");
  const fileName = lastSlash === -1 ? path : path.slice(lastSlash + 1);
  const lastDot = fileName.lastIndexOf(".");
  if (lastDot === -1) {
    return fileName.length > 0;
  }
  return fileName.slice(lastDot + 1).toLowerCase() === "md";
}
function isManagedNoteFile(file) {
  return isManagedNoteLikePath(file.path);
}
function countSiblingManagedNotes(paths, currentPath) {
  const currentDir = currentPath.includes("/") ? currentPath.slice(0, currentPath.lastIndexOf("/")) : "";
  return paths.filter((path) => {
    if (path === currentPath || !isManagedNoteLikePath(path)) {
      return false;
    }
    const dir = path.includes("/") ? path.slice(0, path.lastIndexOf("/")) : "";
    return dir === currentDir;
  }).length;
}

// src/utils/resource-sync-utils.ts
function createEmptyResourceSyncSummary() {
  return {
    movedDirectories: [],
    copiedFiles: [],
    updatedLinks: 0,
    missingResources: [],
    failedTargets: []
  };
}
function formatResourceSyncSummary(summary) {
  const parts = [];
  if (summary.movedDirectories.length > 0) {
    parts.push(`\u5DF2\u79FB\u52A8 ${summary.movedDirectories.length} \u4E2A\u8D44\u6E90\u76EE\u5F55`);
  }
  if (summary.copiedFiles.length > 0) {
    parts.push(`\u5DF2\u590D\u5236 ${summary.copiedFiles.length} \u4E2A\u8D44\u6E90`);
  }
  if (summary.updatedLinks > 0) {
    parts.push(`\u5DF2\u66F4\u65B0 ${summary.updatedLinks} \u4E2A\u94FE\u63A5`);
  }
  if (summary.missingResources.length > 0) {
    parts.push(`${summary.missingResources.length} \u4E2A\u8D44\u6E90\u7F3A\u5931`);
  }
  if (summary.failedTargets.length > 0) {
    parts.push(`${summary.failedTargets.length} \u4E2A\u76EE\u6807\u5904\u7406\u5931\u8D25`);
  }
  return parts.join("\uFF0C");
}

// src/services/directory-move-sync.ts
function createDirectoryMovePlan(input) {
  const wantedDirs = new Set(PathUtils.getManagedResourceDirPrefixes(input.oldDir));
  const directoryMoves = input.availableResourceDirs.filter((dir) => wantedDirs.has(dir)).map((dir) => ({
    from: dir,
    to: PathUtils.mapManagedResourceDir(dir, input.oldDir, input.newDir)
  }));
  return {
    directoryMoves,
    filesToRewrite: input.managedFiles
  };
}
function rewriteDirectoryMoveContent(content, oldDir, newDir) {
  return rewriteManagedResourcePrefix(content, oldDir, newDir);
}
async function syncMovedDirectory(vault, oldDir, newDir, resourceFolderName) {
  const summary = createEmptyResourceSyncSummary();
  const managedFiles = vault.getFiles().filter((file) => isManagedNoteFile(file) && file.path.startsWith(`${newDir}/`));
  const availableResourceDirs = PathUtils.getManagedResourceDirPrefixes(oldDir).map((dir) => ({ logical: dir, actual: PathUtils.resolveManagedResourcePath(vault, resourceFolderName, dir) }));
  for (const candidate of availableResourceDirs) {
    if (!await vault.adapter.exists(candidate.actual)) {
      continue;
    }
    const targetLogical = PathUtils.mapManagedResourceDir(candidate.logical, oldDir, newDir);
    const targetActual = PathUtils.resolveManagedResourcePath(vault, resourceFolderName, targetLogical);
    await vault.adapter.rename(candidate.actual, targetActual);
    summary.movedDirectories.push({ from: candidate.logical, to: targetLogical });
  }
  for (const file of managedFiles) {
    const content = await vault.cachedRead(file);
    const rewrite = rewriteDirectoryMoveContent(content, oldDir, newDir);
    if (rewrite.updatedCount === 0) {
      continue;
    }
    await vault.modify(file, rewrite.content);
    summary.updatedLinks += rewrite.updatedCount;
  }
  return summary;
}

// src/services/note-move-sync.ts
function createNoteMovePlan(input) {
  if (input.siblingManagedNoteCount === 0) {
    return {
      mode: "move-directory",
      copyOperations: []
    };
  }
  return {
    mode: "copy-links",
    copyOperations: input.currentFileLinks.map((link) => {
      const firstSlash = link.indexOf("/", "resources/".length);
      const resourceTypePrefix = firstSlash === -1 ? link : link.slice(0, firstSlash);
      const resourceRelativePath = firstSlash === -1 ? "" : link.slice(firstSlash);
      const oldDirSuffix = input.oldDir ? `/${input.oldDir}` : "";
      return {
        from: link,
        to: resourceRelativePath.startsWith(`${oldDirSuffix}/`) ? `${resourceTypePrefix}/${input.newDir}${resourceRelativePath.slice(oldDirSuffix.length)}` : link
      };
    })
  };
}
async function ensureDirectoryExists(vault, dirPath) {
  if (await vault.adapter.exists(dirPath)) {
    return;
  }
  await vault.adapter.mkdir(dirPath);
}
async function moveDirectory(vault, fromDir, toDir) {
  if (!await vault.adapter.exists(toDir)) {
    await ensureDirectoryExists(vault, toDir.slice(0, toDir.lastIndexOf("/")));
    await vault.adapter.rename(fromDir, toDir);
    return;
  }
  const entries = await vault.adapter.list(fromDir);
  for (const file of entries.files) {
    const target = `${toDir}/${file.slice(file.lastIndexOf("/") + 1)}`;
    await vault.adapter.rename(file, target);
  }
  for (const folder of entries.folders) {
    const target = `${toDir}/${folder.slice(folder.lastIndexOf("/") + 1)}`;
    await moveDirectory(vault, folder, target);
  }
  await vault.adapter.rmdir(fromDir, false);
}
async function syncMovedManagedNote(vault, file, oldPath, resourceFolderName) {
  const summary = createEmptyResourceSyncSummary();
  const oldDir = oldPath.includes("/") ? oldPath.slice(0, oldPath.lastIndexOf("/")) : "";
  const newDir = file.path.includes("/") ? file.path.slice(0, file.path.lastIndexOf("/")) : "";
  const siblingManagedNoteCount = countSiblingManagedNotes(vault.getFiles().map((item) => item.path), oldPath);
  const content = await vault.cachedRead(file);
  const currentFileLinks = listManagedResourcePaths(content);
  const plan = createNoteMovePlan({ oldDir, newDir, currentFileLinks, siblingManagedNoteCount });
  if (plan.mode === "move-directory") {
    for (const resourceDir of PathUtils.getManagedResourceDirPrefixes(oldDir)) {
      const from = PathUtils.resolveManagedResourcePath(vault, resourceFolderName, resourceDir);
      if (!await vault.adapter.exists(from)) {
        continue;
      }
      const targetLogical = PathUtils.mapManagedResourceDir(resourceDir, oldDir, newDir);
      const to = PathUtils.resolveManagedResourcePath(vault, resourceFolderName, targetLogical);
      await moveDirectory(vault, from, to);
      summary.movedDirectories.push({ from: resourceDir, to: targetLogical });
    }
    const rewrite = rewriteManagedResourcePrefix(content, oldDir, newDir);
    if (rewrite.updatedCount > 0) {
      await vault.modify(file, rewrite.content);
      summary.updatedLinks += rewrite.updatedCount;
    }
    return summary;
  }
  let nextContent = content;
  for (const operation of plan.copyOperations) {
    const from = PathUtils.resolveManagedResourcePath(vault, resourceFolderName, operation.from);
    const to = PathUtils.resolveManagedResourcePath(vault, resourceFolderName, operation.to);
    if (!await vault.adapter.exists(from)) {
      summary.missingResources.push(operation.from);
      continue;
    }
    const parent = to.slice(0, to.lastIndexOf("/"));
    await ensureDirectoryExists(vault, parent);
    const bytes = await vault.adapter.readBinary(from);
    await vault.adapter.writeBinary(to, bytes);
    summary.copiedFiles.push(operation);
    nextContent = nextContent.split(operation.from).join(operation.to);
    summary.updatedLinks += 1;
  }
  if (summary.updatedLinks > 0) {
    await vault.modify(file, nextContent);
  }
  return summary;
}

// src/main.ts
var getManagedResourceDirPrefixes = PathUtils.getManagedResourceDirPrefixes;
var mapManagedResourceDir = PathUtils.mapManagedResourceDir;
var SmartAttachmentsPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.pasteHandler = new PasteHandler(this.app.vault, this.settings);
    this.dropHandler = new DropHandler(this.app.vault, this.settings);
    this.registerEvent(
      this.app.workspace.on("editor-paste", (evt, editor, view) => {
        void this.handlePaste(evt, editor, view);
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-drop", (evt, editor, view) => {
        void this.handleDrop(evt, editor, view);
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        void this.handleVaultRename(file, oldPath);
      })
    );
    this.addCommand({
      id: "cleanup-orphaned-attachments",
      name: "\u6E05\u7406\u5B64\u7ACB\u9644\u4EF6",
      callback: () => {
        void this.cleanupOrphanedAttachments();
      }
    });
    this.addSettingTab(new SmartAttachmentsSettingTab(this.app, this));
    console.debug("Smart Attachments plugin loaded");
  }
  onunload() {
    console.debug("Smart Attachments plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.pasteHandler = new PasteHandler(this.app.vault, this.settings);
    this.dropHandler = new DropHandler(this.app.vault, this.settings);
  }
  /**
   * Handle paste event
   */
  async handlePaste(evt, editor, view) {
    const noteFile = view.file;
    if (!noteFile) {
      return;
    }
    if (!isManagedNoteFile(noteFile)) {
      return;
    }
    const handled = await this.pasteHandler.handle(evt, editor, noteFile);
    if (handled) {
      return;
    }
  }
  /**
   * Handle drop event
   */
  async handleDrop(evt, editor, view) {
    const noteFile = view.file;
    if (!noteFile) {
      return;
    }
    if (!isManagedNoteFile(noteFile)) {
      return;
    }
    const handled = await this.dropHandler.handle(evt, editor, noteFile);
    if (handled) {
      return;
    }
  }
  async handleVaultRename(file, oldPath) {
    if (file instanceof import_obsidian5.TFolder) {
      const result = await syncMovedDirectory(this.app.vault, oldPath, file.path, this.settings.resourceFolderName);
      if (result.movedDirectories.length > 0 || result.updatedLinks > 0) {
        new import_obsidian5.Notice(formatResourceSyncSummary(result), 5e3);
      }
      return;
    }
    if (file instanceof import_obsidian5.TFile && isManagedNoteFile(file)) {
      const oldDir = oldPath.includes("/") ? oldPath.slice(0, oldPath.lastIndexOf("/")) : "";
      const newDir = file.path.includes("/") ? file.path.slice(0, file.path.lastIndexOf("/")) : "";
      if (oldDir === newDir) {
        return;
      }
      const result = await syncMovedManagedNote(this.app.vault, file, oldPath, this.settings.resourceFolderName);
      if (result.movedDirectories.length > 0 || result.copiedFiles.length > 0 || result.updatedLinks > 0 || result.missingResources.length > 0) {
        new import_obsidian5.Notice(formatResourceSyncSummary(result), 5e3);
      }
    }
  }
  /**
   * Clean up orphaned attachment files
   */
  async cleanupOrphanedAttachments() {
    const cleanupUtils = new CleanupUtils(this.app.vault, this.settings);
    new import_obsidian5.Notice("\u6B63\u5728\u626B\u63CF\u5B64\u7ACB\u9644\u4EF6...", 3e3);
    try {
      const result = await cleanupUtils.scanOrphanedFiles();
      if (result.orphanedFiles.length === 0) {
        new import_obsidian5.Notice("\u6CA1\u6709\u53D1\u73B0\u5B64\u7ACB\u9644\u4EF6\uFF01", 3e3);
        return;
      }
      if (this.settings.showCleanupConfirmation) {
        new CleanupConfirmModal(
          this.app,
          result.orphanedFiles,
          result.totalSize,
          () => {
            void this.finishCleanup(cleanupUtils, result);
          }
        ).open();
        return;
      }
      await this.finishCleanup(cleanupUtils, result);
    } catch (err) {
      console.error("Error cleaning up orphaned attachments:", err);
      new import_obsidian5.Notice("\u6E05\u7406\u5931\u8D25: " + err.message, 5e3);
    }
  }
  async finishCleanup(cleanupUtils, result) {
    const deleteResult = await cleanupUtils.deleteOrphanedFiles(result.orphanedFiles);
    if (this.settings.showCleanupConfirmation) {
      new CleanupResultModal(this.app, {
        ...result,
        deletedCount: deleteResult.deletedCount,
        deletedSize: deleteResult.deletedSize
      }).open();
    }
    if (deleteResult.deletedCount > 0) {
      const message = this.settings.showCleanupConfirmation ? `\u5DF2\u6E05\u7406 ${deleteResult.deletedCount} \u4E2A\u5B64\u7ACB\u9644\u4EF6\uFF0C\u91CA\u653E ${CleanupUtils.formatFileSize(deleteResult.deletedSize)}` : `\u5DF2\u81EA\u52A8\u6E05\u7406 ${deleteResult.deletedCount} \u4E2A\u5B64\u7ACB\u9644\u4EF6\uFF0C\u91CA\u653E ${CleanupUtils.formatFileSize(deleteResult.deletedSize)}`;
      new import_obsidian5.Notice(message, 5e3);
    }
  }
};
